## NLP In General

Teaching computers how to understand (and generate) human language.

Language & Communication
-----
 1. Speaker
  - Intention  - Goals, Knowledge, Shared Beliefe
  - Generation - tactical
  - Synthesis - text or speech
 2. Listener
  - Perception
  - Iterpretetion - Synactic, semantic, pragmatic
  - Incorporation - Internalization, understanding  
 3. Both
  - Context - Grounding

Basic NLP pipeline
-----

**Language** ----U-----> **Computer** -----G----> L**anguage**

Understanding Text & Context
----

**Question:**

ঢাকা থেকে **বিছানাকান্দি** ভ্রমনের বিস্তারিত তথ্য যেমন: যাতায়াত ব্যবস্থা, থাকার ব্যবস্থা (ভালমানের হোটেল/মোটেল), দর্শনীয় স্থান, খরচ পাতি ইত্যাদি জানতে ইচ্ছুক? 

** Answer 01:**

এর জন্য প্রথমে আপনাকে ঢাকা থেকে সিলেট যেতে হবে,
ঢাকা থেকে সিলেটঃ
ট্রেনঃ ঢাকা থেকে সিলেট যাওয়ার জন্য রাতের ট্রেন কমলাপুর থেকে ছাড়ে রাত ১০টায়। সিলেট পৌঁছায় সকাল ৭টায়। ভাড়া ২৯৫ টাকা।
বাসঃ শ্যামলী,হানিফ, গ্রীন লাইন, সোহাগ, সাউদিয়া, এস আলম, এনা (ঘোড়াশাল-টঙ্গী রুট)। ভাড়া ৪৫০ টাকা।
থাকার হোটেল :
হোটেলঃ সিলেট শহরে থাকার জন্য অনেকভালো মানের হোটেল আছে। শহরের নাইওরপুল এলাকায় হোটেল ফরচুন গার্ডেন (০৮২১-৭১৫৫৯০)।
জেল সড়কে হোটেল ডালাস (০৮২১-৭২০৯৪৫)। ভিআইপি সড়কে হোটেল হিলটাউন (০৮২১-৭১৮২৬৩)। লিঙ্ক রোডে হোটেল গার্ডেন ইন (০৮২১-৮১৪৫০৭)।
আম্বরখানায় হোটেল পলাশ (০৮২১-৭১৮৩০৯)। দরগা এলাকায় হোটেল দরগাগেইট (০৮২১-৭১৭০৬৬)। হোটেল উর্মি (০৮২১-৭১৪৫৬৩)।
জিন্দাবাজারে হোটেল মুন লাইট (০৮২১-৭১৪৮৫০)। তালতলায় গুলশান সেন্টার (০৮২১-৭১০০১৮) ইত্যাদি।
ভাড়া ৩০০ থেকে শুরু করে ৩০০০টাকা পর্যন্ত,নিরাপত্তাও ভাল আছে হোটেলগুলোতে,দরগাগেটে আরো কয়েকটি ভাল হোটেল আছে।
আবার নলজুড়ি উপজেলা সরকারি ডাকবাংলোঃ পূর্ব অনুমতি সাপেক্ষে এইখানে থাকতে পারেন। সরকারি কর্মকর্তা/কর্মচারিদের জন্য প্রতিটি রুম ৫০০টাকা। আর সিভিলিয়ানদের জন্য ১৫০০টাকা।
খাবার :
খাবার রেস্তোরাঃ পানশি, পাঁচ ভাই জনপ্রিয় দুটি রেস্তোরা। এছাড়া আছে উন্ডাল সহ সব নামি-দামি খাবার দোকান।
বিছানা কান্দি :
**বিছানাকান্দি** যেতে হলে সর্বপ্রথম আপনাকে নগরীর আম্বরখানা পয়েন্ট যেতে হবে। সেখানে বিমানবন্দর রোডের দিকে সিএনজি স্টেশন আছে। সিএনজি হাদারঘাট নামক জায়গা পর্যন্ত রিজার্ভ করে গেলে ভাল হয়। পাঁচজন মিলে ৪০০টাকায় সাধারণত ভারা নেওয়া হয়। তবে মানুষ কম থাকলে ৮০টাকা জনপ্রতিও যাওয়া যায়। বিমানবন্দর পর্যন্ত রাস্তা অনেক সুন্দর। চারপাশে শুধু সবুজ চা বাগান। নীল আকাশ আর যেন সবুজ কার্পেটের উপর তাবু টানিয়েছে। বিমানবন্দর থেকে সালুটিকর রাস্তায় প্রবেশ করলেই রাস্তা চরম খারাপ। পিচ ঢালা কালো রাজপথে একটু পরপরই ভাঙ্গা গর্ত। মনে হয় একটু আগেই যেন এ পথে গডজিলা হেটে গিয়েছে। ভারী বালুর ট্রাকগুলো রাস্তার এ দশা করেছে। খারাপ রাস্তা পার হয়েই আপনি একদম গ্রামের ভেতর ঢুকে যাবেন। সিলেটের গ্রামগুলো যেমন সবুজ বৃষ্টিতে ধুয়ে রেখেছে। চিকন রাস্তাগুলো সাপের মতোই আঁকাবাঁকা হয়ে গ্রামের মাঝখানে। গ্রাম দেখতে দেখতে আপনি হাদারঘাট এসে পৌছাবেন। হাদারঘাট বাজারটি খুব একটা বড় না আবার ছোটও না।
ভাড়ার পরিমান কম বেশি হতে পারে।

**Answer 02:**

যেভাবে যাবেন:
ঢাকা থেকে সিলেটে আপনি ট্রেনে বা বাসে করে যেতে পারেন। সিলেট শহরের যে কোন প্রান্ত থেকে রিজার্ভ করা সিএনজি নিয়ে জেতে হবে হাদার বাজার, ভাড়া নেবে বড়জোর ৫০০ টাকা। সিলেটের আম্বরখানা থেকেও যাওয়া যায় আলাদাভাবে। সেখানে প্রতি সিএনজিতে চারজন করে নেয়া হয় হাদার বাজার পর্যন্ত। ভাড়া জনপ্রতি ৮০ টাকা। সময় লাগবে দেড় ঘণ্টার মত। হাদার বাজার নেমে নৌকা ঠিক করতে হবে **বিছানাকান্দি** পর্যন্ত। ভাড়া নেবে ৪০০-৫০০ টাকা আপ ডাউন। স্থানীয়রা ইদানিং পর্যটক বেসি দেখে নৌকার কৃত্রিম সঙ্কট সৃষ্টি করে নৌকা ভাড়া বেশি নিচ্ছে। সেক্ষেত্রে ৮০০-১০০০ টাকা লাগতে পারে। দামাদামি করে উঠবেন, কারণ হাদার বাজার থেকে **বিছানাকান্দির** দুরত্ব খুব একটা বেশি না। ইঞ্জিন চালিত নৌকায় যেতে সর্বোচ্চ ২০ মিনিট লাগে।
যারা ব্যক্তিগত গাড়িতে যাবেন:
সিলেট শহর হতে ৬০ কিলোমিটার উত্তর পূর্বে গোয়াইনঘাট উপজেলার রুস্তমপুর ইউনিয়নে বিছানাকান্দি গ্রাম। সিলেট থেকে ভোলাগঞ্জ মহাসড়ক ধরে সালুটিকর বাজারের ডান দিকে গাড়ী নিয়ে গোয়াইনঘাট লিঙ্ক রোডে হয়ে দেড় ঘন্টা গেলেই আপনি পৌঁছে যাবেন বিছানাকান্দি।
যেখানে থাকবেন:
সিলেট শহরে এখন অনেক গুলো উন্নতমানের হোটেল রয়েছে । বিছানাকান্দিতে দিনে গিয়ে দিনে ফেরা যায় সিলেট শহর থেকে। তাই সিলেট শহরেই থাকতে পারেন। হোটেল হিল টাউন, ব্রিটানিয়া হোটেল, হোটেল দরগা ইন ছাড়াও অনেকগুলো ভাল হোটেল আছে ভিআইপি রোড এবং আম্বরখানা এলাকায়।



Topic - বিছানাকান্দি

Context - ভ্রমন (ঢাকা থেকে বিছানাকান্দি)

Geners Of Text
----

 - Blog
 - Recepie 
 - Chat 
 - Email
 - Medical Record
 - News 

## NLP Applicaions

01. Understanding the sentiment (Sentiment Analysis)
02. Document Clustering (Finding similar document of interest)
03. Intelligent document search

## Beshto Context

Initial Goal
 - Finding Similar document
 - Suggest posts of user interest
 - Meaningful content search result

## Finding Similar post -  Bag-Of-Words approach

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize, word_tokenize
import scipy as sp

from sklearn.feature_extraction import text 


import re
import math

In [2]:
en_posts = ["This is a toy post about machine learning. Actually, it contains not much interesting stuff.",
        "Imaging databases can get huge.",
        "Most imaging databases safe images permanently.",
        "Imaging databases store images.",
        "Imaging databases store images. Imaging databases store images. Imaging databases store images."]
bn_posts = ["মহান মুক্তিযুদ্ধে চূড়ান্ত বিজয়ের মাত্র দুদিন আগে ১৪ ডিসেম্বর এই নারকীয় হত্যাযজ্ঞ ঘটিয়েছিল ঘাতকেরা",
           "আজ ১৪ ডিসেম্বর, শহীদ বুদ্ধিজীবী দিবস",
           "শহীদ বুদ্ধিজীবী স্মৃতিসৌধে সকালে শ্রদ্ধা জানিয়েছেন রাষ্ট্রপতি মো. আবদুল হামিদ ও প্রধানমন্ত্রী শেখ হাসিনা",
           "রপুর ও রায়েরবাজারে বুদ্ধিজীবী স্মৃতিসৌধে অগণিত মানুষ পুষ্পস্তবক অর্পণের মাধ্যমে শ্রদ্ধা নিবেদন করছেন"]

### Converting raw text into a bag-of-words (English)

In [3]:
en_vectorizer = CountVectorizer(min_df=1)
en_vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [4]:
enX_train = en_vectorizer.fit_transform(en_posts)

en_num_samples, en_num_features = enX_train.shape
print("#samples: %d, #features: %d" % (en_num_samples, en_num_features))
print(en_vectorizer.get_feature_names())


#samples: 5, #features: 24
['about', 'actually', 'can', 'contains', 'databases', 'get', 'huge', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'safe', 'store', 'stuff', 'this', 'toy']


In [5]:
en_new_post = "imaging databases"
en_new_post_vec = en_vectorizer.transform([en_new_post])

print(type(en_new_post_vec))
print(en_new_post_vec)  # coo_matrix
print(en_new_post_vec.toarray())

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 4)	1
  (0, 8)	1
[[0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


We **need** to use the **full array** if we want to use it as a vector for similarity calculations. 

For the similarity measurement (the naive one), we calculate the
**Euclidean distance** between the count vectors of the new post and all the old posts as follows:

In [6]:
def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray()) 

# The norm() function calculates the Euclidean norm (shortest distance)

In [7]:
import sys

In [8]:
best_doc = None
best_dist = sys.maxsize
best_i = None

In [9]:
##  "imaging databases"

for i in range(0, en_num_samples):
    en_post = en_posts[i]
    if en_post == en_new_post:
        continue
    en_post_vec = enX_train.getrow(i)
    d = dist_raw(en_post_vec, en_new_post_vec)
    print("=== Post %i with dist=%.2f: \n %s"%(i, d, en_post))
    if d < best_dist:
        best_dist = d
        best_i = i

=== Post 0 with dist=4.00: 
 This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=1.73: 
 Imaging databases can get huge.
=== Post 2 with dist=2.00: 
 Most imaging databases safe images permanently.
=== Post 3 with dist=1.41: 
 Imaging databases store images.
=== Post 4 with dist=5.10: 
 Imaging databases store images. Imaging databases store images. Imaging databases store images.


In [10]:
print("Best post is % i with dist=%.2f"%(best_i, best_dist))

Best post is  3 with dist=1.41


In [11]:
print(enX_train.getrow(3).toarray())
print(enX_train.getrow(4).toarray())

[[0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]]
[[0 0 0 0 3 0 0 3 3 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0]]


### Normalizing the word count vectors

In [12]:
def dist_norm(v1, v2):
    v1_normalized = v1/sp.linalg.norm(v1.toarray())
    v2_normalized = v2/sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())

In [13]:
##  "imaging databases"

for i in range(0, en_num_samples):
    en_post = en_posts[i]
    if en_post == en_new_post:
        continue
    en_post_vec = enX_train.getrow(i)
    d = dist_norm(en_post_vec, en_new_post_vec)
    print("=== Post %i with dist=%.2f: \n %s"%(i, d, en_post))
    if d < best_dist:
        best_dist = d
        best_i = i

=== Post 0 with dist=1.41: 
 This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=0.86: 
 Imaging databases can get huge.
=== Post 2 with dist=0.92: 
 Most imaging databases safe images permanently.
=== Post 3 with dist=0.77: 
 Imaging databases store images.
=== Post 4 with dist=0.77: 
 Imaging databases store images. Imaging databases store images. Imaging databases store images.


### Removing Less important words

In [14]:
en_vectorizer = CountVectorizer(min_df=1, stop_words="english")

In [15]:
##  "imaging databases"

for i in range(0, en_num_samples):
    en_post = en_posts[i]
    if en_post == en_new_post:
        continue
    en_post_vec = enX_train.getrow(i)
    d = dist_raw(en_post_vec, en_new_post_vec)
    print("=== Post %i with dist=%.2f: \n %s"%(i, d, en_post))
    if d < best_dist:
        best_dist = d
        best_i = i
print("Best post is % i with dist=%.2f"%(best_i, best_dist))

=== Post 0 with dist=4.00: 
 This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=1.73: 
 Imaging databases can get huge.
=== Post 2 with dist=2.00: 
 Most imaging databases safe images permanently.
=== Post 3 with dist=1.41: 
 Imaging databases store images.
=== Post 4 with dist=5.10: 
 Imaging databases store images. Imaging databases store images. Imaging databases store images.
Best post is  3 with dist=0.77


Overall, it has, however, not changed much as our
posts are kept short for demonstration purposes. It will become vital when we look
at real-world data.

### Stemming

In [16]:
import nltk.stem
s= nltk.stem.SnowballStemmer('english')

In [17]:
print(s.stem("graphics"))

graphic


In [18]:
print(s.stem("imaging"))

imag


Extending the vectorizer with NLTK's stemmer
----

In [19]:
english_stemmer = nltk.stem.SnowballStemmer('english')

class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [20]:
en_vectorizer = StemmedCountVectorizer(min_df=1, stop_words='english')

enX_train = en_vectorizer.fit_transform(en_posts)

en_num_samples, en_num_features = enX_train.shape

print("#samples: %d, #features: %d" % (en_num_samples, en_num_features))
print(en_vectorizer.get_feature_names())

en_new_post = "imaging databases"
en_new_post_vec = en_vectorizer.transform([en_new_post])

#samples: 5, #features: 14
['actual', 'contain', 'databas', 'huge', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'safe', 'store', 'stuff', 'toy']


In [21]:
##  "imaging databases"

for i in range(0, en_num_samples):
    en_post = en_posts[i]
    if en_post == en_new_post:
        continue
    en_post_vec = enX_train.getrow(i)
    d = dist_norm(en_post_vec, en_new_post_vec)
    print("=== Post %i with dist=%.2f: \n %s"%(i, d, en_post))
    if d < best_dist:
        best_dist = d
        best_i = i
print("Best post is % i with dist=%.2f"%(best_i, best_dist))

=== Post 0 with dist=1.41: 
 This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=0.61: 
 Imaging databases can get huge.
=== Post 2 with dist=0.63: 
 Most imaging databases safe images permanently.
=== Post 3 with dist=0.52: 
 Imaging databases store images.
=== Post 4 with dist=0.52: 
 Imaging databases store images. Imaging databases store images. Imaging databases store images.
Best post is  3 with dist=0.52


### TF-IDF

Now that we have a reasonable way to extract a compact vector from a noisy textual post.

Let us step back for a while to think about what the feature values
actually mean.

The feature values simply count occurrences of terms in a post. 

We silently assumed that higher values for a term also mean that the term is of greater importance to the
given post.

But in rality higher number of occurence doesn't mean the word is important. Important word normally appear less in the document.

So if we ant to give importance to the rally important words we have to use TF-IDF.


TF stands for the counting part, while IDF factors in the discounting.

Here is a simple implementation - 

In [22]:
import math
def tfidf(term, doc, docset):
    tf = float(doc.count(term))/sum(w.count(term) for w in docset)
    idf = math.log(float(len(docset))/ 
                   (len([doc for doc in docset if term in doc])))
    return tf * idf

In [23]:
a, abb, abc = ["a"], ["a", "b", "b"], ["a", "b", "c"]
D = [a, abb, abc]
print(tfidf("a", a, D))

0.0


In [24]:
print(tfidf("b", abb, D))

0.27031007207210955


In [25]:
print(tfidf("c", abc, D))

1.0986122886681098


TfidfVectorizer
--

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

class StemmedTfidfVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(TfidfVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [27]:
en_vectorizer = StemmedTfidfVectorizer(min_df=1, stop_words='english')

enX_train = en_vectorizer.fit_transform(en_posts)

en_num_samples, en_num_features = enX_train.shape

print("#samples: %d, #features: %d" % (en_num_samples, en_num_features))
print(en_vectorizer.get_feature_names())

en_new_post = "imaging databases"
en_new_post_vec = en_vectorizer.transform([en_new_post])

#samples: 5, #features: 14
['actual', 'contain', 'databas', 'huge', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'safe', 'store', 'stuff', 'toy']


In [28]:
##  "imaging databases"

for i in range(0, en_num_samples):
    en_post = en_posts[i]
    if en_post == en_new_post:
        continue
    en_post_vec = enX_train.getrow(i)
    d = dist_norm(en_post_vec, en_new_post_vec)
    print("=== Post %i with dist=%.2f: \n %s"%(i, d, en_post))
    if d < best_dist:
        best_dist = d
        best_i = i
print("Best post is % i with dist=%.2f"%(best_i, best_dist))

=== Post 0 with dist=1.41: 
 This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=0.87: 
 Imaging databases can get huge.
=== Post 2 with dist=0.86: 
 Most imaging databases safe images permanently.
=== Post 3 with dist=0.63: 
 Imaging databases store images.
=== Post 4 with dist=0.63: 
 Imaging databases store images. Imaging databases store images. Imaging databases store images.
Best post is  3 with dist=0.52


In [29]:
print(enX_train.toarray().transpose())

[[ 0.35355339  0.          0.          0.          0.        ]
 [ 0.35355339  0.          0.          0.          0.        ]
 [ 0.          0.440627    0.29746628  0.37660107  0.37660107]
 [ 0.          0.78210977  0.          0.          0.        ]
 [ 0.          0.440627    0.59493255  0.75320213  0.75320213]
 [ 0.35355339  0.          0.          0.          0.        ]
 [ 0.35355339  0.          0.          0.          0.        ]
 [ 0.35355339  0.          0.          0.          0.        ]
 [ 0.          0.          0.52800051  0.          0.        ]
 [ 0.35355339  0.          0.          0.          0.        ]
 [ 0.          0.          0.52800051  0.          0.        ]
 [ 0.          0.          0.          0.5393127   0.5393127 ]
 [ 0.35355339  0.          0.          0.          0.        ]
 [ 0.35355339  0.          0.          0.          0.        ]]


### Learning so far

01. Tokenizing the text
 - CountVectorizer
02. Remove Stopwords
03. Throwing away rare words
04. Calculating TF-IDF values from the counts, considering the whole text crpus.

## Finding Similar post in bangla

In [30]:
bn_posts = ["মহান মুক্তিযুদ্ধে চূড়ান্ত বিজয়ের মাত্র দুদিন আগে ১৪ ডিসেম্বর এই নারকীয় হত্যাযজ্ঞ ঘটিয়েছিল ঘাতকেরা",
           "আজ ১৪ ডিসেম্বর, শহীদ বুদ্ধিজীবী দিবস",
           "শহীদ বুদ্ধিজীবী স্মৃতিসৌধে সকালে শ্রদ্ধা জানিয়েছেন রাষ্ট্রপতি মো. আবদুল হামিদ ও প্রধানমন্ত্রী শেখ হাসিনা",
           "রপুর ও রায়েরবাজারে বুদ্ধিজীবী স্মৃতিসৌধে অগণিত মানুষ পুষ্পস্তবক অর্পণের মাধ্যমে শ্রদ্ধা নিবেদন করছেন"]

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from nltk.tokenize import sent_tokenize, word_tokenize
import scipy as sp

from sklearn.feature_extraction import text 

import re
import math
import sys

In [32]:
def stem(word):
    regexp = r'^(.*?)(ে| ের|েই|দের|ছিলেন|ির|ীয়|েও|টি|ও|তে|কে|গুলি|গুলো|গুলা|ছিলেন|ছিল|লেন|কের|ছেন|েরা)?$'
    stem, suffix = re.findall(regexp, word)[0]
    return stem

In [33]:
with open('bn_stopwords.txt') as f: 
    bn_stopwords = [line.rstrip('\n') for line in f]
    
print(bn_stopwords[:30])

['আগে', 'মাত্র', 'আই', 'অতএব', 'আগামী', 'অবধি', 'অনুযায়ী', 'আদ্যভাগে', 'এই', 'একই', 'একে', 'একটি', 'এখন', 'এখনও', 'এখানে', 'এখানেই', 'এটি', 'এটা', 'এটাই', 'এতটাই', 'এবং', 'একবার', 'এবার', 'এদের', 'এঁদের', 'এমন', 'এমনকী', 'এল', 'এর', 'এরা']


In [34]:
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (stem(w) for w in analyzer(doc))

In [35]:
class StemmedTfidfVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedTfidfVectorizer, self).build_analyzer()
        return lambda doc: (stem(w) for w in analyzer(doc))

In [36]:
vectorizer = StemmedTfidfVectorizer(min_df=1, tokenizer=word_tokenize,
                                   stop_words=bn_stopwords)

In [37]:
X_train = vectorizer.fit_transform(bn_posts)
num_samples, num_features = X_train.shape

print(vectorizer.get_feature_names())
print("#samples: %d, #features: %d" % (num_samples, num_features))

[',', '.', 'অগণিত', 'অর্পণের', 'আজ', 'আবদুল', 'ঘটিয়ে', 'ঘাতক', 'চূড়ান্ত', 'জানিয়ে', 'ডিসেম্বর', 'দিবস', 'দুদিন', 'নারক', 'নিবেদন', 'পুষ্পস্তবক', 'প্রধানমন্ত্রী', 'বিজয়ের', 'বুদ্ধিজীবী', 'মহান', 'মানুষ', 'মুক্তিযুদ্ধ', 'মো', 'রপুর', 'রাষ্ট্রপতি', 'রায়েরবাজার', 'শহীদ', 'শেখ', 'শ্রদ্ধা', 'সকাল', 'স্মৃতিসৌধ', 'হত্যাযজ্ঞ', 'হামিদ', 'হাসিনা', '১৪']
#samples: 4, #features: 35


In [38]:
X_train.toarray().transpose()

array([[ 0.        ,  0.43551643,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.28545588,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.33999849],
       [ 0.        ,  0.        ,  0.        ,  0.33999849],
       [ 0.        ,  0.43551643,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.28545588,  0.        ],
       [ 0.31245141,  0.        ,  0.        ,  0.        ],
       [ 0.31245141,  0.        ,  0.        ,  0.        ],
       [ 0.31245141,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.28545588,  0.        ],
       [ 0.24634028,  0.34336615,  0.        ,  0.        ],
       [ 0.        ,  0.43551643,  0.        ,  0.        ],
       [ 0.31245141,  0.        ,  0.        ,  0.        ],
       [ 0.31245141,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.33999849],
       [ 0.        ,  0.        ,  0.        ,  0.33999849],
       [ 0.        ,  0.

In [39]:
new_post = "শহীদ বুদ্ধিজীবী দিবস" # "রায়েরবাজার" #
new_post_vec = vectorizer.transform([new_post])

In [40]:
def dist_norm(v1, v2):
    v1_normalized = v1/sp.linalg.norm(v1.toarray())
    v2_normalized = v2/sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())

In [41]:
best_doc = None
best_dist = sys.maxsize
best_i = None

for i in range(0, num_samples):
    post = bn_posts[i]
    if post == new_post:
        continue
    post_vec = X_train.getrow(i)
    d = dist_norm(post_vec, new_post_vec)
    print("=== Post %i with dist=%.2f: %s"%(i, d, post))
    if d < best_dist:
        best_dist = d
        best_i = i
    
print("======  ======\n Best post is % i with dist =% .2f"%(best_i, best_dist))

=== Post 0 with dist=1.41: মহান মুক্তিযুদ্ধে চূড়ান্ত বিজয়ের মাত্র দুদিন আগে ১৪ ডিসেম্বর এই নারকীয় হত্যাযজ্ঞ ঘটিয়েছিল ঘাতকেরা
=== Post 1 with dist=0.87: আজ ১৪ ডিসেম্বর, শহীদ বুদ্ধিজীবী দিবস
=== Post 2 with dist=1.26: শহীদ বুদ্ধিজীবী স্মৃতিসৌধে সকালে শ্রদ্ধা জানিয়েছেন রাষ্ট্রপতি মো. আবদুল হামিদ ও প্রধানমন্ত্রী শেখ হাসিনা
=== Post 3 with dist=1.34: রপুর ও রায়েরবাজারে বুদ্ধিজীবী স্মৃতিসৌধে অগণিত মানুষ পুষ্পস্তবক অর্পণের মাধ্যমে শ্রদ্ধা নিবেদন করছেন
======  ======
 Best post is  1 with dist = 0.87
